Without a dataset

In [ ]:
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
x = 2 * np.random.rand(100, 1)
y = 2 + 3 * x + np.random.randn(100, 1)

In [ ]:
x

In [ ]:
y

In [ ]:
D_model = keras.Sequential(layers.Dense(units = 1, input_dim=1, activation = 'linear'))#input_dim = 1 is model working on single variavle

In [ ]:
D_model.compile(optimizer='sgd', loss='mean_squared_error') #sgd = stochastic gradient discriminent

In [ ]:
D_model.fit(x, y, epochs=100, batch_size=32) #epochs is number of iterations and batchsize refers to no.of samples considered in one iteration

Epoch 1/100
4/4 [==============================] - 0s 4ms/step - loss: 15.2902
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 10.3366
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 6.9879
Epoch 4/100
4/4 [==============================] - 0s 2ms/step - loss: 4.9557
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 3.6212
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 2.7685
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 2.2040
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 1.8490
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 1.5829
Epoch 10/100
4/4 [==============================] - 0s 2ms/step - loss: 1.4323
Epoch 11/100
4/4 [==============================] - 0s 4ms/step - loss: 1.3441
Epoch 12/100
4/4 [==============================] - 0s 3ms/step - loss: 1.2449
Epoch 13/100
4/4 [==============================] - 0s 2ms/

In [ ]:
new_data = np.array([[3.0], [3.0]])#giving a sample input to generate predictions
predictions = D_model.predict(new_data)
print("Predictions:")
print(predictions)

1/1 [==============================] - 0s 13ms/step
Predictions:
[[11.726954]
 [11.726954]]


**On dataset**

In [ ]:
dataset = pd.read_csv('/content/Salary_Data.csv')
data = dataset.copy()

In [ ]:
x = data['YearsExperience']
y = data['Salary']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=32)

In [ ]:
model = keras.Sequential([layers.Dense(units=1,input_dim=1, activation='linear')])
model.compile(optimizer='sgd', loss ='mean_squared_error')

In [ ]:
model.fit(x_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
1/1 [==============================] - 0s 166ms/step - loss: 6481782784.0000
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 633484480.0000
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 188316832.0000
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 153517472.0000
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 149893824.0000
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 148646688.0000
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 147588784.0000
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 146553920.0000
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 145529344.0000
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 144514032.0000
Epoch 11/100
1/1 [==============================] - 0s 7ms/step - loss: 143507872.0000
Epoch 12/100
1/1 [==============================]

In [ ]:
predict = model.predict(x_test)

1/1 [==============================] - 0s 27ms/step


In [ ]:
predictions = predict.reshape(-1,1)
predictions

array([[ 23304.867],
       [ 58811.58 ],
       [ 45792.453],
       [ 57628.023],
       [ 94318.3  ],
       [ 68280.04 ],
       [134559.23 ],
       [116805.88 ],
       [ 73014.27 ],
       [ 80115.62 ]], dtype=float32)

In [ ]:
actual_vals = np.array(y_test)
actual_vals

array([ 39343.,  57081.,  60150.,  56957.,  98273.,  67938., 121872.,
       105582.,  83088.,  81363.])

In [ ]:
result = pd.DataFrame(predictions, columns=['predicted'])
result['actual'] = actual_vals
result

predicted    actual
0   23304.867188   39343.0
1   58811.578125   57081.0
2   45792.453125   60150.0
3   57628.023438   56957.0
4   94318.296875   98273.0
5   68280.039062   67938.0
6  134559.234375  121872.0
7  116805.882812  105582.0
8   73014.273438   83088.0
9   80115.617188   81363.0